name: anya
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Services
  intl: 0.16.1
  # Service locator
  get_it: ^5.0.0
  # Logger by Google developers
  logging: ^0.11.4
  # Manage routes
  sailor: ^0.7.1
  # Render SVG file
  flutter_svg: ^0.19.0
  # Bloc for state management
  flutter_bloc: ^6.0.5
  # Value equality
  equatable: ^1.2.5
  # Local cache
  shared_preferences: ^0.5.10
  # Http client
  dio: ^3.0.10
  # Information of application package
  package_info: ^0.4.3
  # Information of device
  device_info: ^0.4.2+7
  # Device timezone
  flutter_native_timezone: ^1.0.4
  # Functional programming
  dartz: ^0.9.1
  # Quick animation
  division: 0.8.8
  # Flutter Icon Changer
  flutter_launcher_icons: ^0.8.1
  # Same page hero animation
  flutter_sidekick: ^0.1.3
  # Liquid indicator
  liquid_progress_indicator: ^0.3.2
  # Custom slider
  syncfusion_flutter_sliders: ^18.3.51-beta
  # Custom bottom sheet
  draggable_bottom_sheet: ^0.1.1
  # Audio player
  assets_audio_player: ^2.0.13+1
  # Spin Kit
  flutter_spinkit: ^4.1.2+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audios/
    - assets/icons/
    - assets/fonts/rubik/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
